---
title: "Homework5_KSalmons"
author: "Kaytlyn Salmons"
date: "2022-11-30"
output: pdf_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tigris) 
library(dplyr) 
library(sf) 
library(ggplot2)
library(stats)
library(ggthemes)
library(forcats)
library(scales)
library(tidyverse)
```


```{r homicide data}
homicides <- read.csv(url("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"))
```

```{r recoding the homicide outcomes , echo=TRUE}
homicides$disp_unsolved = (homicides$disposition !="Closed by arrest")
head(homicides)
```

```{r filter Philly , echo=TRUE}
Philly_killy <- 
  filter(homicides, city=="Philadelphia")
```

```{r map of census tracts in Philly, echo=TRUE}
Phil_map <- tracts("PA", "Philadelphia")
```


```{r plot murders, echo=TRUE, fig.height=10, fig.width=10}
philly <- ggplot() +
  geom_sf(data = Phil_map) +
  geom_point(data = Philly_killy, size=0.4, aes(x=lon, y=lat, col= fct_lump(victim_race, n=3))) +
  labs(x = "Longitude", y = "Latitude", title= "Homicides in Philadelphia", col = "Victim Race")+
theme_few()
philly_labels <- as_labeller(c('FALSE' = "Solved",
  'TRUE' = "Unsolved"))
philly + facet_wrap(~disp_unsolved, ncol = 1, labeller = philly_labels)
```



